# Generated by Django 5.0.1 on 2024-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('answer_flag', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
