# Generated by Django 5.0.1 on 2024-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.SlugField(default='aaa', unique=True),
            preserve_default=False,
        ),
    ]
