# Generated by Django 5.0.1 on 2024-02-06 12:19

import django.db.models.deletion
import interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platoon',
            field=models.ForeignKey(default=interface.models.Platoon.get_default_platoon, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='interface.platoon'),
        ),
    ]
