# Generated by Django 5.0.1 on 2024-01-31 09:09

import django_summernote.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_lab_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.AlterField(
            model_name='lab',
            name='answer_flag',
            field=models.CharField(max_length=1024, null=True, verbose_name='Ответный флаг'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Название в адресной строке'),
        ),
    ]
